
# Error codes/messages for consistent backend handling
ERR_UNKNOWN_CHAR = "Unknown character"
ERR_UNTERM_BLOCK_COMMENT = "Unterminated block comment at EOF"
ERR_INVALID_NEGATIVE = "Invalid negative number (expected digit after '-')"
ERR_IDENT_STARTS_WITH_DIGIT = "Invalid token: identifier cannot start with a digit (e.g., '1x')"
ERR_FLOAT_MULTIPLE_DOTS = "Invalid float: multiple '.'"
ERR_STRING_BAD_ESCAPE = "Invalid escape in string"
ERR_CHAR_UNTERMINATED = "Unterminated char literal"
ERR_CHAR_EMPTY = "Empty char literal"
ERR_CHAR_EXPECT_QUOTE = "Expected closing ' in char literal"
ERR_CHAR_BAD_ESCAPE = "Invalid escape in char literal"
ERR_CHAR_EXPECT_QUOTE_AFTER_ESCAPE = "Expected closing ' after escape"
ERR_SINGLE_AND = "Unexpected '&' (expected '&&')"
ERR_SINGLE_OR = "Unexpected '|' (expected '||')"
ERR_IDENT_TOO_LONG = "Identifier exceeds maximum length"
ERR_INT_TOO_LONG = "Integer exceeds maximum digit length"
ERR_FLOAT_INT_TOO_LONG = "Float integer part exceeds maximum digit length"
ERR_FLOAT_FRAC_TOO_LONG = "Float fractional part exceeds maximum digit length"
