PRODUCTIONS = [
    (1, '<program>', ['<global>', '<program_body>']),
    (2, '<program_body>', ['wall', 'id', '(', '<param_list>', ')', '{', '<func_body>', '}', '<program_body>']),
    (3, '<program_body>', ['<return_type>', '<program_body2>']),
    (4, '<program_body2>', ['id', '(', '<param_list>', ')', '{', '<func_body>', '}', '<program_body>']),
    (5, '<program_body2>', ['blueprint', '(', ')', '{', '<func_body>', '}']),
    (6, '<global>', ['roof', '<global_dec>', ';', '<global>']),
    (7, '<global>', ['λ']),
    (8, '<global_dec>', ['<global_var>']),
    (9, '<global_dec>', ['<structure>']),
    (10, '<global_dec>', ['<global_const>']),
    (11, '<global_var>', ['<data_type>', 'id', '<global_end>']),
    (12, '<global_var>', ['wall', 'id', '<global_wall_end>']),
    (13, '<data_type>', ['tile']),
    (14, '<data_type>', ['glass']),
    (15, '<data_type>', ['brick']),
    (16, '<data_type>', ['beam']),
    (17, '<global_end>', ['<global_init>', '<global_mult>']),
    (18, '<global_end>', ['<array_dec>']),
    (19, '<global_init>', ['=', '<value>']),
    (20, '<global_init>', ['λ']),
    (21, '<global_mult>', [',', 'id', '<global_init>', '<global_mult>']),
    (22, '<global_mult>', ['λ']),
    (23, '<value>', ['tile_lit']),
    (24, '<value>', ['glass_lit']),
    (25, '<value>', ['brick_lit']),
    (26, '<value>', ['solid']),
    (27, '<value>', ['fragile']),
    (28, '<array_dec>', ['[', '<arr_size>']),
    (29, '<arr_size>', [']', '<one_d_end>']),
    (30, '<arr_size>', ['tile_lit', ']', '<one_d_end2>']),
    (31, '<one_d_end>', ['[', 'tile_lit', ']', '=', '{', '{', '<elements>', '}', '<mult_elem2>', '}']),
    (32, '<one_d_end>', ['=', '{', '<elements>', '}']),
    (33, '<one_d_end2>', ['[', 'tile_lit', ']', '<two_d_end>']),
    (34, '<one_d_end2>', ['=', '{', '<elements>', '}']),
    (35, '<one_d_end2>', ['λ']),
    (36, '<two_d_end>', ['=', '{', '{', '<elements>', '}', '<mult_elem2>', '}']),
    (37, '<two_d_end>', ['λ']),
    (38, '<elements>', ['<value>', '<mult_elem>']),
    (39, '<mult_elem>', [',', '<value>', '<mult_elem>']),
    (40, '<mult_elem>', ['λ']),
    (41, '<mult_elem2>', [',', '{', '<elements>', '}', '<mult_elem2>']),
    (42, '<mult_elem2>', ['λ']),
    (43, '<global_wall_end>', ['<global_wall_init>', '<global_mult_wall>']),
    (44, '<global_wall_end>', ['<wall_array>']),
    (45, '<global_wall_init>', ['=', 'wall_lit']),
    (46, '<global_wall_init>', ['λ']),
    (47, '<global_mult_wall>', [',', 'id', '<global_wall_init>', '<global_mult_wall>']),
    (48, '<global_mult_wall>', ['λ']),
    (49, '<wall_array>', ['[', '<wall_size>']),
    (50, '<wall_size>', [']', '<wall_one_d_end>']),
    (51, '<wall_size>', ['tile_lit', ']', '<wall_one_d_end2>']),
    (52, '<wall_one_d_end>', ['[', 'tile_lit', ']', '=', '{', '{', '<wall_elem>', '}', '<wall_mult_elem2>', '}']),
    (53, '<wall_one_d_end>', ['=', '{', '<wall_elem>', '}']),
    (54, '<wall_one_d_end2>', ['[', 'tile_lit', ']', '<wall_two_d_end>']),
    (55, '<wall_one_d_end2>', ['=', '{', '<wall_elem>', '}']),
    (56, '<wall_one_d_end2>', ['λ']),
    (57, '<wall_two_d_end>', ['=', '{', '{', '<wall_elem>', '}', '<wall_mult_elem2>', '}']),
    (58, '<wall_two_d_end>', ['λ']),
    (59, '<wall_elem>', ['wall_lit', '<wall_mult_elem>']),
    (60, '<wall_mult_elem>', [',', 'wall_lit', '<wall_mult_elem>']),
    (61, '<wall_mult_elem>', ['λ']),
    (62, '<wall_mult_elem2>', [',', '{', '<wall_elem>', '}', '<wall_mult_elem2>']),
    (63, '<wall_mult_elem2>', ['λ']),
    (64, '<structure>', ['house', 'id', '<struct_type>']),
    (65, '<struct_type>', ['<struct_dec>']),
    (66, '<struct_type>', ['<struct_var>']),
    (67, '<struct_dec>', ['{', '<struct_members>', '}', '<struct_id_end>']),
    (68, '<struct_members>', ['<data_type_dec>', '<array>', ';', '<mult_members>']),
    (69, '<data_type_dec>', ['<data_type>', 'id']),
    (70, '<data_type_dec>', ['wall', 'id']),
    (71, '<array>', ['[', 'tile_lit', ']', '<array2>']),
    (72, '<array>', ['λ']),
    (73, '<array2>', ['[', 'tile_lit', ']']),
    (74, '<array2>', ['λ']),
    (75, '<mult_members>', ['<data_type_dec>', '<array>', ';', '<mult_members>']),
    (76, '<mult_members>', ['λ']),
    (77, '<struct_id_end>', ['id', '<struct_init>', '<mult_struct_id>']),
    (78, '<struct_id_end>', ['λ']),
    (79, '<struct_init>', ['=', '{', '<struct_elem>', '}']),
    (80, '<struct_init>', ['λ']),
    (81, '<struct_elem>', ['<struct_value>', '<mult_struct_elem>']),
    (82, '<struct_elem>', ['{', '<struct_arr_elem>', '}', '<mult_struct_elem>']),
    (83, '<struct_value>', ['<value>']),
    (84, '<struct_value>', ['wall_lit']),
    (85, '<mult_struct_elem>', [',', '<struct_elem>']),
    (86, '<mult_struct_elem>', ['λ']),
    (87, '<struct_arr_elem>', ['<struct_elements>']),
    (88, '<struct_arr_elem>', ['{', '<struct_elements>', '}', '<struct_mult_elem2>']),
    (89, '<struct_elements>', ['<struct_value>', '<struct_mult_elem>']),
    (90, '<struct_mult_elem>', [',', '<struct_value>']),
    (91, '<struct_mult_elem>', ['λ']),
    (92, '<struct_mult_elem2>', [',', '{', '<struct_elements>', '}', '<struct_mult_elem2>']),
    (93, '<struct_mult_elem2>', ['λ']),
    (94, '<mult_struct_id>', [',', 'id', '<struct_init>', '<mult_struct_id>']),
    (95, '<mult_struct_id>', ['λ']),
    (96, '<struct_var>', ['id', '<struct_init>', '<mult_struct_id>']),
    (97, '<global_const>', ['cement', '<global_const_type>']),
    (98, '<global_const_type>', ['<data_type>', 'id', '<global_const_end>']),
    (99, '<global_const_type>', ['wall', 'id', '<g_const_wall_end>']),
    (100, '<global_const_type>', ['house', 'id', 'id', '=', '{', '<struct_elem>', '}', '<global_const_struct>']),
    (101, '<global_const_end>', ['=', '<value>', '<global_mult_const>']),
    (102, '<global_const_end>', ['[', 'tile_lit', ']', '<global_const_end2>']),
    (103, '<global_mult_const>', [',', 'id', '=', '<value>', '<global_mult_const>']),
    (104, '<global_mult_const>', ['λ']),
    (105, '<global_const_end2>', ['=', '{', '<elements>', '}']),
    (106, '<global_const_end2>', ['[', 'tile_lit', ']', '=', '{', '{', '<elements>', '}', '<mult_elem2>', '}']),
    (107, '<g_const_wall_end>', ['=', 'wall_lit', '<g_mult_const_wall>']),
    (108, '<g_const_wall_end>', ['[', 'tile_lit', ']', '<g_const_wall_end2>']),
    (109, '<g_mult_const_wall>', [',', 'id', '=', 'wall_lit', '<g_mult_const_wall>']),
    (110, '<g_mult_const_wall>', ['λ']),
    (111, '<g_const_wall_end2>', ['=', '{', '<wall_elem>', '}']),
    (112, '<g_const_wall_end2>', ['[', 'tile_lit', ']', '=', '{', '{', '<wall_elem>', '}', '<wall_mult_elem2>', '}']),
    (113, '<global_const_struct>', [',', 'id', '=', '{', '<struct_elem>', '}', '<global_const_struct>']),
    (114, '<global_const_struct>', ['λ']),
    (115, '<return_type>', ['<data_type>']),
    (116, '<return_type>', ['field']),
    (117, '<param_list>', ['<data_type_dec>', '<mult_param>']),
    (118, '<param_list>', ['λ']),
    (119, '<mult_param>', [',', '<data_type_dec>', '<mult_param>']),
    (120, '<mult_param>', ['λ']),
    (121, '<func_body>', ['<local>', '<func_body2>']),
    (122, '<func_body>', ['<statement>', '<func_body2>']),
    (123, '<func_body2>', ['<func_body>']),
    (124, '<func_body2>', ['λ']),
    (125, '<local>', ['<declaration>', ';']),
    (126, '<declaration>', ['<variable>']),
    (127, '<declaration>', ['<structure>']),
    (128, '<declaration>', ['<constant>']),
    (129, '<variable>', ['<data_type>', 'id', '<var_end>']),
    (130, '<variable>', ['wall', 'id', '<wall_end>']),
    (131, '<var_end>', ['<initializer>', '<mult_var>']),
    (132, '<var_end>', ['<array_dec>']),
    (133, '<initializer>', ['=', '<init_value>']),
    (134, '<initializer>', ['λ']),
    (135, '<mult_var>', [',', 'id', '<initializer>', '<mult_var>']),
    (136, '<mult_var>', ['λ']),
    (137, '<wall_end>', ['<wall_initializer>', '<mult_wall>']),
    (138, '<wall_end>', ['<wall_array>']),
    (139, '<wall_initializer>', ['=', '<wall_init>']),
    (140, '<wall_initializer>', ['λ']),
    (141, '<wall_init>', ['(', '<wall_init>', ')']),
    (142, '<wall_init>', ['wall_lit', '<wall_op>']),
    (143, '<wall_init>', ['brick_lit', '+', 'wall_lit', '<wall_op>']),
    (144, '<wall_init>', ['id', '<id_type>', '<wall_op>']),
    (145, '<wall_op>', ['+', '(', '<wall_init>', ')']),
    (146, '<wall_op>', ['+', 'wall_lit', '<wall_op>']),
    (147, '<wall_op>', ['+', 'brick_lit', '<wall_op>']),
    (148, '<wall_op>', ['+', 'id', '<id_type>', '<wall_op>']),
    (149, '<wall_op>', ['λ']),
    (150, '<mult_wall>', [',', 'id', '<wall_initializer>', '<mult_wall>']),
    (151, '<mult_wall>', ['λ']),
    (152, '<constant>', ['cement', '<const_type>']),
    (153, '<const_type>', ['<data_type>', 'id', '<const_end>']),
    (154, '<const_type>', ['wall', 'id', '<const_wall_end>']),
    (155, '<const_type>', ['house', 'id', 'id', '=', '{', '<struct_elem>', '}', '<mult_const_struct>']),
    (156, '<const_end>', ['=', '<init_value>', '<mult_const>']),
    (157, '<const_end>', ['[', 'tile_lit', ']', '<global_const_end2>']),
    (158, '<mult_const>', [',', 'id', '=', '<init_value>', '<mult_const>']),
    (159, '<mult_const>', ['λ']),
    (160, '<const_wall_end>', ['=', '<wall_init>', '<mult_wall>']),
    (161, '<const_wall_end>', ['[', 'tile_lit', ']', '<g_const_wall_end2>']),
    (162, '<mult_const_struct>', [',', 'id', '=', '{', '<struct_elem>', '}', '<mult_const_struct>']),
    (163, '<mult_const_struct>', ['λ']),
    (164, '<init_value>', ['<value_exp>', '<exp_op>']),
    (165, '<init_value>', ['<prefix_op>', '<id_val>', '<exp_op>']),
    (166, '<value_exp>', ['<value_type>']),
    (167, '<value_exp>', ['<group>']),
    (168, '<value_exp>', ['-', '<negative_type>']),
    (169, '<value_type>', ['id', '<id_type>']),
    (170, '<value_type>', ['<value>']),
    (171, '<id_type>', ['<id_type2>']),
    (172, '<id_type>', ['λ']),
    (173, '<id_type2>', ['<arr_struct>', '<postfix_op>']),
    (174, '<id_type2>', ['<func_call>']),
    (175, '<arr_struct>', ['<array_index>']),
    (176, '<arr_struct>', ['<struct_id>']),
    (177, '<arr_struct>', ['λ']),
    (178, '<array_index>', ['[', '<init_value>', ']', '<array_index2>']),
    (179, '<array_index>', ['λ']),
    (180, '<array_index2>', ['[', '<init_value>', ']']),
    (181, '<array_index2>', ['λ']),
    (182, '<struct_id>', ['.', 'id', '<array_index>']),
    (183, '<struct_id>', ['λ']),
    (184, '<func_call>', ['(', '<func_argu>', ')']),
    (185, '<func_call>', ['λ']),
    (186, '<func_argu>', ['<init_value>', '<func_mult_call>']),
    (187, '<func_argu>', ['<wall_init>', '<func_mult_call>']),
    (188, '<func_argu>', ['λ']),
    (189, '<func_mult_call>', [',', '<init_value>', '<func_mult_call>']),
    (190, '<func_mult_call>', [',', '<wall_init>', '<func_mult_call>']),
    (191, '<func_mult_call>', ['λ']),
    (192, '<postfix_op>', ['<unary_op>']),
    (193, '<postfix_op>', ['λ']),
    (194, '<unary_op>', ['++']),
    (195, '<unary_op>', ['--']),
    (196, '<group>', ['(', '<init_value>', ')']),
    (197, '<negative_type>', ['<value_type>']),
    (198, '<negative_type>', ['<group>']),
    (199, '<exp_op>', ['<operator>', '<init_value>']),
    (200, '<exp_op>', ['λ']),
    (201, '<prefix_op>', ['!']),
    (202, '<prefix_op>', ['<unary_op>']),
    (203, '<id_val>', ['id', '<id_type3>']),
    (204, '<id_type3>', ['<array_index>']),
    (205, '<id_type3>', ['<struct_id>']),
    (206, '<id_type3>', ['λ']),
    (207, '<operator>', ['+']),
    (208, '<operator>', ['-']),
    (209, '<operator>', ['*']),
    (210, '<operator>', ['/']),
    (211, '<operator>', ['%']),
    (212, '<operator>', ['<']),
    (213, '<operator>', ['<=']),
    (214, '<operator>', ['>']),
    (215, '<operator>', ['>=']),
    (216, '<operator>', ['==']),
    (217, '<operator>', ['!=']),
    (218, '<operator>', ['&&']),
    (219, '<operator>', ['||']),
    (220, '<statement>', ['<io_statement>']),
    (221, '<statement>', ['<assign_statement>']),
    (222, '<statement>', ['<if_statement>']),
    (223, '<statement>', ['<switch_statement>']),
    (224, '<statement>', ['<for_statement>']),
    (225, '<statement>', ['<while_statement>']),
    (226, '<statement>', ['<dowhile_statement>']),
    (227, '<statement>', ['<break_statement>']),
    (228, '<statement>', ['<continue_statement>']),
    (229, '<statement>', ['<return_statement>']),
    (230, '<io_statement>', ['write', '(', 'wall_lit', ',', '<write_argu>', ')', ';']),
    (231, '<io_statement>', ['view', '(', 'wall_lit', '<view_argu>', ')', ';']),
    (232, '<write_argu>', ['&', '<id_val>', '<mult_write_argu>']),
    (233, '<write_argu>', ['<id_val>', '<mult_write_argu>']),
    (234, '<mult_write_argu>', [',', '<write_argu>']),
    (235, '<mult_write_argu>', ['λ']),
    (236, '<view_argu>', [',', '<home_value>', '<mult_view_argu>']),
    (237, '<view_argu>', ['λ']),
    (238, '<mult_view_argu>', ['<view_argu>']),
    (239, '<mult_view_argu>', ['λ']),
    (240, '<assign_statement>', ['<unary_op>', 'id', ';']),
    (241, '<assign_statement>', ['id', '<id_type4>', ';']),
    (242, '<id_type4>', ['(', '<func_argu>', ')']),
    (243, '<id_type4>', ['<unary_op>']),
    (244, '<id_type4>', ['<id_type3>', '<assign_op>', '<assign_value>']),
    (245, '<assign_value>', ['<init_value>']),
    (246, '<assign_value>', ['<wall_init>']),
    (247, '<assign_op>', ['=']),
    (248, '<assign_op>', ['+=']),
    (249, '<assign_op>', ['-=']),
    (250, '<assign_op>', ['*=']),
    (251, '<assign_op>', ['/=']),
    (252, '<assign_op>', ['%=']),
    (253, '<if_statement>', ['if', '(', '<init_value>', ')', '{', '<func_body>', '}', '<else_statement>']),
    (254, '<else_statement>', ['else', '<else_statement2>']),
    (255, '<else_statement>', ['λ']),
    (256, '<else_statement2>', ['<if_statement>']),
    (257, '<else_statement2>', ['{', '<func_body>', '}']),
    (258, '<switch_statement>', ['room', '(', '<init_value>', ')', '{', '<switch_body>', '}']),
    (259, '<switch_body>', ['door', '<case_exp>', ':', '<case_body>', '<mult_switch_body>']),
    (260, '<switch_body>', ['ground', ':', '<case_body>']),
    (261, '<mult_switch_body>', ['<switch_body>']),
    (262, '<mult_switch_body>', ['λ']),
    (263, '<case_exp>', ['<case_type>', '<case_op>']),
    (264, '<case_type>', ['<case_val>']),
    (265, '<case_type>', ['<case_group>']),
    (266, '<case_type>', ['-', '<case_negative>']),
    (267, '<case_val>', ['tile_lit']),
    (268, '<case_val>', ['brick_lit']),
    (269, '<case_val>', ['solid']),
    (270, '<case_val>', ['fragile']),
    (271, '<case_group>', ['(', '<case_exp>', ')']),
    (272, '<case_negative>', ['<case_val>']),
    (273, '<case_negative>', ['<case_group>']),
    (274, '<case_op>', ['<operator>', '<case_exp>']),
    (275, '<case_op>', ['λ']),
    (276, '<case_body>', ['<statement>', '<mult_smt>']),
    (277, '<case_body>', ['{', '<func_body>', '}']),
    (278, '<case_body>', ['λ']),
    (279, '<mult_smt>', ['<statement>']),
    (280, '<mult_smt>', ['λ']),
    (281, '<for_statement>', ['for', '(', '<for_dec>', ';', '<init_value>', ';', '<init_value>', ')', '{', '<func_body>', '}']),
    (282, '<for_dec>', ['<data_type>', 'id', '<initializer>']),
    (283, '<for_dec>', ['id', '<initializer>']),
    (284, '<while_statement>', ['while', '(', '<init_value>', ')', '{', '<func_body>', '}']),
    (285, '<dowhile_statement>', ['do', '{', '<func_body>', '}', 'while', '(', '<init_value>', ')', ';']),
    (286, '<break_statement>', ['crack', ';']),
    (287, '<continue_statement>', ['mend', ';']),
    (288, '<return_statement>', ['home', '<home_value>', ';']),
    (289, '<home_value>', ['<init_value>']),
    (290, '<home_value>', ['<wall_init>']),
]