PRODUCTIONS = [
    (1, '<program>', ['<global>', '<program_body>']),
    (2, '<program_body>', ['wall', 'id', '(', '<param_list>', ')', '{', '<func_body>', '}', '<program_body>']),
    (3, '<program_body>', ['<return_type>', '<program_body2>']),
    (4, '<program_body2>', ['id', '(', '<param_list>', ')', '{', '<func_body>', '}', '<program_body>']),
    (5, '<program_body2>', ['blueprint', '(', ')', '{', '<func_body>', '}']),
    (6, '<global>', ['roof', '<global_dec>', ';', '<global>']),
    (7, '<global>', ['λ']),
    (8, '<global_dec>', ['<global_var>']),
    (9, '<global_dec>', ['<structure>']),
    (10, '<global_dec>', ['<global_const>']),
    (11, '<global_var>', ['<data_type>', 'id', '<global_end>']),
    (12, '<global_var>', ['wall', 'id', '<global_wall_end>']),
    (13, '<data_type>', ['tile']),
    (14, '<data_type>', ['glass']),
    (15, '<data_type>', ['brick']),
    (16, '<data_type>', ['beam']),
    (17, '<global_end>', ['<global_init>', '<global_mult>']),
    (18, '<global_end>', ['<array_dec>']),
    (19, '<global_init>', ['=', '<value>']),
    (20, '<global_init>', ['λ']),
    (21, '<global_mult>', [',', 'id', '<global_init>', '<global_mult>']),
    (22, '<global_mult>', ['λ']),
    (23, '<value>', ['tile_lit']),
    (24, '<value>', ['glass_lit']),
    (25, '<value>', ['brick_lit']),
    (26, '<value>', ['solid']),
    (27, '<value>', ['fragile']),
    (28, '<array_dec>', ['[', '<arr_size>']),
    (29, '<arr_size>', [']', '<one_d_end>']),
    (30, '<arr_size>', ['tile_lit', ']', '<one_d_end2>']),
    (31, '<one_d_end>', ['[', 'tile_lit', ']', '=', '{', '{', '<elements>', '}', '<mult_elem2>', '}']),
    (32, '<one_d_end>', ['=', '{', '<elements>', '}']),
    (33, '<one_d_end2>', ['[', 'tile_lit', ']', '<two_d_end>']),
    (34, '<one_d_end2>', ['=', '{', '<elements>', '}']),
    (35, '<one_d_end2>', ['λ']),
    (36, '<two_d_end>', ['=', '{', '{', '<elements>', '}', '<mult_elem2>', '}']),
    (37, '<two_d_end>', ['λ']),
    (38, '<elements>', ['<value>', '<mult_elem>']),
    (39, '<mult_elem>', [',', '<value>', '<mult_elem>']),
    (40, '<mult_elem>', ['λ']),
    (41, '<mult_elem2>', [',', '{', '<elements>', '}', '<mult_elem2>']),
    (42, '<mult_elem2>', ['λ']),
    (43, '<global_wall_end>', ['<global_wall_init>', '<global_mult_wall>']),
    (44, '<global_wall_end>', ['<wall_array>']),
    (45, '<global_wall_init>', ['=', 'wall_lit']),
    (46, '<global_wall_init>', ['λ']),
    (47, '<global_mult_wall>', [',', 'id', '<global_wall_init>', '<global_mult_wall>']),
    (48, '<global_mult_wall>', ['λ']),
    (49, '<wall_array>', ['[', '<wall_size>']),
    (50, '<wall_size>', [']', '<wall_one_d_end>']),
    (51, '<wall_size>', ['tile_lit', ']', '<wall_one_d_end2>']),
    (52, '<wall_one_d_end>', ['[', 'tile_lit', ']', '=', '{', '{', '<wall_elem>', '}', '<wall_mult_elem2>', '}']),
    (53, '<wall_one_d_end>', ['=', '{', '<wall_elem>', '}']),
    (54, '<wall_one_d_end2>', ['[', 'tile_lit', ']', '<wall_two_d_end>']),
    (55, '<wall_one_d_end2>', ['=', '{', '<wall_elem>', '}']),
    (56, '<wall_one_d_end2>', ['λ']),
    (57, '<wall_two_d_end>', ['=', '{', '{', '<wall_elem>', '}', '<wall_mult_elem2>', '}']),
    (58, '<wall_two_d_end>', ['λ']),
    (59, '<wall_elem>', ['wall_lit', '<wall_mult_elem>']),
    (60, '<wall_mult_elem>', [',', 'wall_lit', '<wall_mult_elem>']),
    (61, '<wall_mult_elem>', ['λ']),
    (62, '<wall_mult_elem2>', [',', '{', '<wall_elem>', '}', '<wall_mult_elem2>']),
    (63, '<wall_mult_elem2>', ['λ']),
    (64, '<structure>', ['house', 'id', '<struct_type>']),
    (65, '<struct_type>', ['<struct_dec>']),
    (66, '<struct_type>', ['<struct_var>']),
    (67, '<struct_dec>', ['{', '<struct_members>', '}', '<struct_id_end>']),
    (68, '<struct_members>', ['<data_type_dec>', '<array>', ';', '<mult_members>']),
    (69, '<data_type_dec>', ['<data_type>', 'id']),
    (70, '<data_type_dec>', ['wall', 'id']),
    (71, '<array>', ['[', 'tile_lit', ']', '<array2>']),
    (72, '<array>', ['λ']),
    (73, '<array2>', ['[', 'tile_lit', ']']),
    (74, '<array2>', ['λ']),
    (75, '<mult_members>', ['<data_type_dec>', '<array>', ';', '<mult_members>']),
    (76, '<mult_members>', ['λ']),
    (77, '<struct_id_end>', ['id', '<struct_init>', '<mult_struct_id>']),
    (78, '<struct_id_end>', ['λ']),
    (79, '<struct_init>', ['=', '{', '<struct_elem>', '}']),
    (80, '<struct_init>', ['λ']),
    (81, '<struct_elem>', ['<struct_value>', '<mult_struct_elem>']),
    (82, '<struct_elem>', ['{', '<struct_arr_elem>', '}', '<mult_struct_elem>']),
    (83, '<struct_value>', ['<value>']),
    (84, '<struct_value>', ['wall_lit']),
    (85, '<mult_struct_elem>', [',', '<struct_elem>']),
    (86, '<mult_struct_elem>', ['λ']),
    (87, '<struct_arr_elem>', ['<struct_elements>']),
    (88, '<struct_arr_elem>', ['{', '<struct_elements>', '}', '<struct_mult_elem2>']),
    (89, '<struct_elements>', ['<struct_value>', '<struct_mult_elem>']),
    (90, '<struct_mult_elem>', [',', '<struct_value>', '<struct_mult_elem>']),
    (91, '<struct_mult_elem>', ['λ']),
    (92, '<struct_mult_elem2>', [',', '{', '<struct_elements>', '}', '<struct_mult_elem2>']),
    (93, '<struct_mult_elem2>', ['λ']),
    (94, '<mult_struct_id>', [',', 'id', '<struct_init>', '<mult_struct_id>']),
    (95, '<mult_struct_id>', ['λ']),
    (96, '<struct_var>', ['id', '<struct_init>', '<mult_struct_id>']),
    (97, '<global_const>', ['cement', '<global_const_type>']),
    (98, '<global_const_type>', ['<data_type>', 'id', '<global_const_end>']),
    (99, '<global_const_type>', ['wall', 'id', '<g_const_wall_end>']),
    (100, '<global_const_type>', ['house', 'id', 'id', '=', '{', '<struct_elem>', '}', '<global_const_struct>']),
    (101, '<global_const_end>', ['=', '<value>', '<global_mult_const>']),
    (102, '<global_const_end>', ['[', 'tile_lit', ']', '<global_const_end2>']),
    (103, '<global_mult_const>', [',', 'id', '=', '<value>', '<global_mult_const>']),
    (104, '<global_mult_const>', ['λ']),
    (105, '<global_const_end2>', ['=', '{', '<elements>', '}']),
    (106, '<global_const_end2>', ['[', 'tile_lit', ']', '=', '{', '{', '<elements>', '}', '<mult_elem2>', '}']),
    (107, '<g_const_wall_end>', ['=', 'wall_lit', '<g_mult_const_wall>']),
    (108, '<g_const_wall_end>', ['[', 'tile_lit', ']', '<g_const_wall_end2>']),
    (109, '<g_mult_const_wall>', [',', 'id', '=', 'wall_lit', '<g_mult_const_wall>']),
    (110, '<g_mult_const_wall>', ['λ']),
    (111, '<g_const_wall_end2>', ['=', '{', '<wall_elem>', '}']),
    (112, '<g_const_wall_end2>', ['[', 'tile_lit', ']', '=', '{', '{', '<wall_elem>', '}', '<wall_mult_elem2>', '}']),
    (113, '<global_const_struct>', [',', 'id', '=', '{', '<struct_elem>', '}', '<global_const_struct>']),
    (114, '<global_const_struct>', ['λ']),
    (115, '<return_type>', ['<data_type>']),
    (116, '<return_type>', ['field']),
    (117, '<param_list>', ['<data_type_dec>', '<mult_param>']),
    (118, '<param_list>', ['λ']),
    (119, '<mult_param>', [',', '<data_type_dec>', '<mult_param>']),
    (120, '<mult_param>', ['λ']),
    (121, '<func_body>', ['<local>', '<func_body2>']),
    (122, '<func_body>', ['<statement>', '<func_body2>']),
    (123, '<func_body2>', ['<func_body>']),
    (124, '<func_body2>', ['λ']),
    (125, '<local>', ['<declaration>', ';']),
    (126, '<declaration>', ['<variable>']),
    (127, '<declaration>', ['<structure>']),
    (128, '<declaration>', ['<constant>']),
    (129, '<variable>', ['<data_type>', 'id', '<var_end>']),
    (130, '<variable>', ['wall', 'id', '<wall_end>']),
    (131, '<var_end>', ['<initializer>', '<mult_var>']),
    (132, '<var_end>', ['<array_dec>']),
    (133, '<initializer>', ['=', '<expression>']),
    (134, '<initializer>', ['λ']),
    (135, '<mult_var>', [',', 'id', '<initializer>', '<mult_var>']),
    (136, '<mult_var>', ['λ']),
    (137, '<expression>', ['id', '<id_type>', '<exp_op>']),
    (138, '<expression>', ['(', '<expression>', ')', '<exp_op>']),
    (139, '<expression>', ['<value_exp>', '<exp_op>']),
    (140, '<expression>', ['<prefix_op>', '<id_val>', '<exp_op>']),
    (141, '<value_exp>', ['<value>']),
    (142, '<value_exp>', ['-', '<expression>']),
    (143, '<id_type>', ['<id_type2>']),
    (144, '<id_type>', ['λ']),
    (145, '<id_type2>', ['<arr_struct>', '<postfix_op>']),
    (146, '<id_type2>', ['<func_call>']),
    (147, '<arr_struct>', ['<array_index>']),
    (148, '<arr_struct>', ['<struct_id>']),
    (149, '<array_index>', ['[', '<expression>', ']', '<array_index2>']),
    (150, '<array_index>', ['λ']),
    (151, '<array_index2>', ['[', '<expression>', ']']),
    (152, '<array_index2>', ['λ']),
    (153, '<struct_id>', ['.', 'id', '<array_index>']),
    (154, '<struct_id>', ['λ']),
    (155, '<func_call>', ['(', '<func_argu>', ')']),
    (156, '<func_call>', ['λ']),
    (157, '<func_argu>', ['<assign_rhs>', '<func_mult_call>']),
    (158, '<func_argu>', ['λ']),
    (159, '<func_mult_call>', [',', '<assign_rhs>', '<func_mult_call>']),
    (160, '<func_mult_call>', ['λ']),
    (161, '<postfix_op>', ['<unary_op>']),
    (162, '<postfix_op>', ['λ']),
    (163, '<unary_op>', ['++']),
    (164, '<unary_op>', ['--']),
    (165, '<exp_op>', ['<operator>', '<expression>']),
    (166, '<exp_op>', ['λ']),
    (167, '<prefix_op>', ['!']),
    (168, '<prefix_op>', ['<unary_op>']),
    (169, '<id_val>', ['id', '<id_type3>']),
    (170, '<id_type3>', ['<array_index>']),
    (171, '<id_type3>', ['<struct_id>']),
    (172, '<id_type3>', ['λ']),
    (173, '<operator>', ['+']),
    (174, '<operator>', ['-']),
    (175, '<operator>', ['*']),
    (176, '<operator>', ['/']),
    (177, '<operator>', ['%']),
    (178, '<operator>', ['<']),
    (179, '<operator>', ['<=']),
    (180, '<operator>', ['>']),
    (181, '<operator>', ['>=']),
    (182, '<operator>', ['==']),
    (183, '<operator>', ['!=']),
    (184, '<operator>', ['&&']),
    (185, '<operator>', ['||']),
    (186, '<wall_end>', ['<wall_initializer>', '<mult_wall>']),
    (187, '<wall_end>', ['<wall_array>']),
    (188, '<wall_initializer>', ['=', '<wall_init>']),
    (189, '<wall_initializer>', ['λ']),
    (190, '<wall_init>', ['(', '<wall_init>', ')', '<wall_op>']),
    (191, '<wall_init>', ['wall_lit', '<wall_op>']),
    (192, '<wall_init>', ['id', '<id_type>', '<wall_op>']),
    (193, '<wall_op>', ['+', '<wall_init>']),
    (194, '<wall_op>', ['λ']),
    (195, '<mult_wall>', [',', 'id', '<wall_initializer>', '<mult_wall>']),
    (196, '<mult_wall>', ['λ']),
    (197, '<constant>', ['cement', '<const_type>']),
    (198, '<const_type>', ['<data_type>', 'id', '<const_end>']),
    (199, '<const_type>', ['wall', 'id', '<const_wall_end>']),
    (200, '<const_type>', ['house', 'id', 'id', '=', '{', '<struct_elem>', '}', '<mult_const_struct>']),
    (201, '<const_end>', ['=', '<expression>', '<mult_const>']),
    (202, '<const_end>', ['[', 'tile_lit', ']', '<global_const_end2>']),
    (203, '<mult_const>', [',', 'id', '=', '<expression>', '<mult_const>']),
    (204, '<mult_const>', ['λ']),
    (205, '<const_wall_end>', ['=', '<wall_init>', '<mult_wall>']),
    (206, '<const_wall_end>', ['[', 'tile_lit', ']', '<g_const_wall_end2>']),
    (207, '<mult_const_struct>', [',', 'id', '=', '{', '<struct_elem>', '}', '<mult_const_struct>']),
    (208, '<mult_const_struct>', ['λ']),
    (209, '<statement>', ['<io_statement>']),
    (210, '<statement>', ['<assign_statement>']),
    (211, '<statement>', ['<if_statement>']),
    (212, '<statement>', ['<switch_statement>']),
    (213, '<statement>', ['<for_statement>']),
    (214, '<statement>', ['<while_statement>']),
    (215, '<statement>', ['<dowhile_statement>']),
    (216, '<statement>', ['<break_statement>']),
    (217, '<statement>', ['<continue_statement>']),
    (218, '<statement>', ['<return_statement>']),
    (219, '<io_statement>', ['write', '(', 'wall_lit', ',', '<write_argu>', ')', ';']),
    (220, '<io_statement>', ['view', '(', 'wall_lit', '<view_argu>', ')', ';']),
    (221, '<write_argu>', ['&', '<id_val>', '<mult_write_argu>']),
    (222, '<write_argu>', ['<id_val>', '<mult_write_argu>']),
    (223, '<mult_write_argu>', [',', '<write_argu>']),
    (224, '<mult_write_argu>', ['λ']),
    (225, '<view_argu>', [',', '<assign_rhs>', '<mult_view_argu>']),
    (226, '<view_argu>', ['λ']),
    (227, '<mult_view_argu>', ['<view_argu>']),
    (228, '<mult_view_argu>', ['λ']),
    (229, '<assign_statement>', ['<unary_op>', 'id', ';']),
    (230, '<assign_statement>', ['id', '<id_type4>', ';']),
    (231, '<id_type4>', ['(', '<func_argu>', ')']),
    (232, '<id_type4>', ['<unary_op>']),
    (233, '<id_type4>', ['<id_type3>', '<assign_end>']),
    (234, '<assign_end>', ['<compound_op>', '<expression>']),
    (235, '<assign_end>', ['=', '<assign_rhs>']),
    (236, '<compound_op>', ['+=']),
    (237, '<compound_op>', ['-=']),
    (238, '<compound_op>', ['*=']),
    (239, '<compound_op>', ['/=']),
    (240, '<compound_op>', ['%=']),
    (241, '<assign_rhs>', ['id', '<id_type>', '<assign_exp>']),
    (242, '<assign_rhs>', ['(', '<assign_rhs>', ')', '<assign_exp>']),
    (243, '<assign_rhs>', ['<value_exp>', '<assign_exp>']),
    (244, '<assign_rhs>', ['<operator>', '<assign_rhs>']),
    (245, '<assign_rhs>', ['wall_lit', '<assign_exp>']),
    (246, '<assign_exp>', ['<operator>', '<assign_rhs>']),
    (247, '<assign_exp>', ['λ']),
    (248, '<if_statement>', ['if', '(', '<expression>', ')', '{', '<func_body>', '}', '<else_statement>']),
    (249, '<else_statement>', ['else', '<else_statement2>']),
    (250, '<else_statement>', ['λ']),
    (251, '<else_statement2>', ['<if_statement>']),
    (252, '<else_statement2>', ['{', '<func_body>', '}']),
    (253, '<switch_statement>', ['room', '(', '<expression>', ')', '{', '<switch_body>', '}']),
    (254, '<switch_body>', ['door', '<case_exp>', ':', '<case_body>', '<mult_switch_body>']),
    (255, '<switch_body>', ['ground', ':', '<case_body>']),
    (256, '<mult_switch_body>', ['<switch_body>']),
    (257, '<mult_switch_body>', ['λ']),
    (258, '<case_exp>', ['<case_type>', '<case_op>']),
    (259, '<case_type>', ['<case_val>']),
    (260, '<case_type>', ['<case_group>']),
    (261, '<case_type>', ['-', '<case_negative>']),
    (262, '<case_val>', ['tile_lit']),
    (263, '<case_val>', ['brick_lit']),
    (264, '<case_val>', ['solid']),
    (265, '<case_val>', ['fragile']),
    (266, '<case_group>', ['(', '<case_exp>', ')']),
    (267, '<case_negative>', ['<case_val>']),
    (268, '<case_negative>', ['<case_group>']),
    (269, '<case_op>', ['<operator>', '<case_exp>']),
    (270, '<case_op>', ['λ']),
    (271, '<case_body>', ['<statement>', '<mult_smt>']),
    (272, '<case_body>', ['{', '<func_body>', '}']),
    (273, '<case_body>', ['λ']),
    (274, '<mult_smt>', ['<statement>']),
    (275, '<mult_smt>', ['λ']),
    (276, '<for_statement>', ['for', '(', '<for_dec>', ';', '<expression>', ';', '<expression>', ')', '{', '<func_body>', '}']),
    (277, '<for_dec>', ['<data_type>', 'id', '<initializer>']),
    (278, '<for_dec>', ['id', '<initializer>']),
    (279, '<while_statement>', ['while', '(', '<expression>', ')', '{', '<func_body>', '}']),
    (280, '<dowhile_statement>', ['do', '{', '<func_body>', '}', 'while', '(', '<expression>', ')', ';']),
    (281, '<break_statement>', ['crack', ';']),
    (282, '<continue_statement>', ['mend', ';']),
    (283, '<return_statement>', ['home', '<assign_rhs>', ';']),
]