FOLLOW_SET = {
    '<program>': {'$'},
    '<program_body>': {'$'},
    '<program_body2>': {'$'},
    '<global>': {'wall', 'tile', 'glass', 'brick', 'beam', 'field'},
    '<global_dec>': {';'},
    '<global_var>': {';'},
    '<data_type>': {'id', 'blueprint'},
    '<global_end>': {';'},
    '<global_init>': {';', ','},
    '<global_mult>': {';'},
    '<value>': {')', '}', ';', ',', ']', '+', '-', '*', '/', '%', '<', '<=', '>', '>=', '==', '!=', '&&', '||'},
    '<array_dec>': {';'},
    '<arr_size>': {';'},
    '<one_d_end>': {';'},
    '<one_d_end2>': {';'},
    '<two_d_end>': {';'},
    '<elements>': {'}'},
    '<mult_elem>': {'}'},
    '<mult_elem2>': {'}'},
    '<global_wall_end>': {';'},
    '<global_wall_init>': {';', ','},
    '<global_mult_wall>': {';'},
    '<wall_array>': {';'},
    '<wall_size>': {';'},
    '<wall_one_d_end>': {';'},
    '<wall_one_d_end2>': {';'},
    '<wall_two_d_end>': {';'},
    '<wall_elem>': {'}'},
    '<wall_mult_elem>': {'}'},
    '<wall_mult_elem2>': {'}'},
    '<structure>': {';'},
    '<struct_type>': {';'},
    '<struct_dec>': {';'},
    '<struct_members>': {'}'},
    '<data_type_dec>': {')', ';', ',', '['},
    '<array>': {';'},
    '<array2>': {';'},
    '<mult_members>': {'}'},
    '<struct_id_end>': {';'},
    '<struct_init>': {';', ','},
    '<struct_elem>': {'}'},
    '<struct_value>': {'}', ','},
    '<mult_struct_elem>': {'}'},
    '<struct_arr_elem>': {'}'},
    '<struct_elements>': {'}'},
    '<struct_mult_elem>': {'}'},
    '<struct_mult_elem2>': {'}'},
    '<mult_struct_id>': {';'},
    '<struct_var>': {';'},
    '<global_const>': {';'},
    '<global_const_type>': {';'},
    '<global_const_end>': {';'},
    '<global_mult_const>': {';'},
    '<global_const_end2>': {';'},
    '<g_const_wall_end>': {';'},
    '<g_mult_const_wall>': {';'},
    '<g_const_wall_end2>': {';'},
    '<global_const_struct>': {';'},
    '<return_type>': {'id', 'blueprint'},
    '<param_list>': {')'},
    '<mult_param>': {')'},
    '<func_body>': {'}'},
    '<func_body2>': {'}'},
    '<local>': {'wall', 'id', '}', 'tile', 'glass', 'brick', 'beam', 'house', 'cement', '++', '--', 'write', 'view', 'if', 'room', 'for', 'while', 'do', 'crack', 'mend'},
    '<declaration>': {';'},
    '<variable>': {';'},
    '<var_end>': {';'},
    '<initializer>': {';', ','},
    '<mult_var>': {';'},
    '<wall_end>': {';'},
    '<wall_initializer>': {';', ','},
    '<wall_init>': {')', ';', ','},
    '<wall_op>': {')', ';', ','},
    '<mult_wall>': {';'},
    '<constant>': {';'},
    '<const_type>': {';'},
    '<const_end>': {';'},
    '<mult_const>': {';'},
    '<const_wall_end>': {';'},
    '<mult_const_struct>': {';'},
    '<init_value>': {')', ';', ',', ']'},
    '<value_exp>': {')', ';', ',', ']', '+', '-', '*', '/', '%', '<', '<=', '>', '>=', '==', '!=', '&&', '||'},
    '<value_type>': {')', ';', ',', ']', '+', '-', '*', '/', '%', '<', '<=', '>', '>=', '==', '!=', '&&', '||'},
    '<id_type>': {')', ';', ',', ']', '+', '-', '*', '/', '%', '<', '<=', '>', '>=', '==', '!=', '&&', '||'},
    '<id_type2>': {')', ';', ',', ']', '+', '-', '*', '/', '%', '<', '<=', '>', '>=', '==', '!=', '&&', '||'},
    '<arr_struct>': {')', ';', ',', ']', '+', '-', '++', '--', '*', '/', '%', '<', '<=', '>', '>=', '==', '!=', '&&', '||'},
    '<array_index>': {')', ';', '=', ',', ']', '+', '-', '++', '--', '*', '/', '%', '<', '<=', '>', '>=', '==', '!=', '&&', '||', '+=', '-=', '*=', '/=', '%='},
    '<array_index2>': {')', ';', '=', ',', ']', '+', '-', '++', '--', '*', '/', '%', '<', '<=', '>', '>=', '==', '!=', '&&', '||', '+=', '-=', '*=', '/=', '%='},
    '<struct_id>': {')', ';', '=', ',', ']', '+', '-', '++', '--', '*', '/', '%', '<', '<=', '>', '>=', '==', '!=', '&&', '||', '+=', '-=', '*=', '/=', '%='},
    '<func_call>': {')', ';', ',', ']', '+', '-', '*', '/', '%', '<', '<=', '>', '>=', '==', '!=', '&&', '||'},
    '<func_argu>': {')'},
    '<func_mult_call>': {')'},
    '<postfix_op>': {')', ';', ',', ']', '+', '-', '*', '/', '%', '<', '<=', '>', '>=', '==', '!=', '&&', '||'},
    '<unary_op>': {'id', ')', ';', ',', ']', '+', '-', '*', '/', '%', '<', '<=', '>', '>=', '==', '!=', '&&', '||'},
    '<group>': {')', ';', ',', ']', '+', '-', '*', '/', '%', '<', '<=', '>', '>=', '==', '!=', '&&', '||'},
    '<negative_type>': {')', ';', ',', ']', '+', '-', '*', '/', '%', '<', '<=', '>', '>=', '==', '!=', '&&', '||'},
    '<exp_op>': {')', ';', ',', ']'},
    '<prefix_op>': {'id'},
    '<id_val>': {')', ';', ',', ']', '+', '-', '*', '/', '%', '<', '<=', '>', '>=', '==', '!=', '&&', '||'},
    '<id_type3>': {')', ';', '=', ',', ']', '+', '-', '*', '/', '%', '<', '<=', '>', '>=', '==', '!=', '&&', '||', '+=', '-=', '*=', '/=', '%='},
    '<operator>': {'id', '(', 'tile_lit', 'glass_lit', 'brick_lit', 'solid', 'fragile', '-', '++', '--', '!'},
    '<statement>': {'wall', 'id', '}', 'tile', 'glass', 'brick', 'beam', 'house', 'cement', '++', '--', 'write', 'view', 'if', 'room', 'door', 'ground', 'for', 'while', 'do', 'crack', 'mend', 'home'},
    '<io_statement>': {'wall', 'id', '}', 'tile', 'glass', 'brick', 'beam', 'house', 'cement', '++', '--', 'write', 'view', 'if', 'room', 'door', 'ground', 'for', 'while', 'do', 'crack', 'mend', 'home'},
    '<write_argu>': {')'},
    '<mult_write_argu>': {')'},
    '<view_argu>': {')'},
    '<mult_view_argu>': {')'},
    '<assign_statement>': {'wall', 'id', '}', 'tile', 'glass', 'brick', 'beam', 'house', 'cement', '++', '--', 'write', 'view', 'if', 'room', 'door', 'ground', 'for', 'while', 'do', 'crack', 'mend', 'home'},
    '<id_type4>': {';'},
    '<assign_value>': {';'},
    '<assign_op>': {'id', '(', 'tile_lit', 'glass_lit', 'brick_lit', 'solid', 'fragile', 'wall_lit', '-', '++', '--', '!'},
    '<if_statement>': {'wall', 'id', '}', 'tile', 'glass', 'brick', 'beam', 'house', 'cement', '++', '--', 'write', 'view', 'if', 'room', 'door', 'ground', 'for', 'while', 'do', 'crack', 'mend', 'home'},
    '<else_statement>': {'wall', 'id', '}', 'tile', 'glass', 'brick', 'beam', 'house', 'cement', '++', '--', 'write', 'view', 'if', 'room', 'door', 'ground', 'for', 'while', 'do', 'crack', 'mend', 'home'},
    '<else_statement2>': {'wall', 'id', '}', 'tile', 'glass', 'brick', 'beam', 'house', 'cement', '++', '--', 'write', 'view', 'if', 'room', 'door', 'ground', 'for', 'while', 'do', 'crack', 'mend', 'home'},
    '<switch_statement>': {'wall', 'id', '}', 'tile', 'glass', 'brick', 'beam', 'house', 'cement', '++', '--', 'write', 'view', 'if', 'room', 'door', 'ground', 'for', 'while', 'do', 'crack', 'mend', 'home'},
    '<switch_body>': {'}'},
    '<mult_switch_body>': {'}'},
    '<case_exp>': {')', ':'},
    '<case_type>': {'}', '+', '-', '*', '/', '%', '<', '<=', '>', '>=', '==', '!=', '&&', '||', ':'},
    '<case_val>': {'}', '+', '-', '*', '/', '%', '<', '<=', '>', '>=', '==', '!=', '&&', '||', ':'},
    '<case_group>': {'}', '+', '-', '*', '/', '%', '<', '<=', '>', '>=', '==', '!=', '&&', '||', ':'},
    '<case_negative>': {'}', '+', '-', '*', '/', '%', '<', '<=', '>', '>=', '==', '!=', '&&', '||', ':'},
    '<case_op>': {')', ':'},
    '<case_body>': {'}', 'door', 'ground'},
    '<mult_smt>': {'}', 'door', 'ground'},
    '<for_statement>': {'wall', 'id', '}', 'tile', 'glass', 'brick', 'beam', 'house', 'cement', '++', '--', 'write', 'view', 'if', 'room', 'door', 'ground', 'for', 'while', 'do', 'crack', 'mend', 'home'},
    '<for_dec>': {';'},
    '<while_statement>': {'wall', 'id', '}', 'tile', 'glass', 'brick', 'beam', 'house', 'cement', '++', '--', 'write', 'view', 'if', 'room', 'door', 'ground', 'for', 'while', 'do', 'crack', 'mend', 'home'},
    '<dowhile_statement>': {'wall', 'id', '}', 'tile', 'glass', 'brick', 'beam', 'house', 'cement', '++', '--', 'write', 'view', 'if', 'room', 'door', 'ground', 'for', 'while', 'do', 'crack', 'mend', 'home'},
    '<break_statement>': {'wall', 'id', '}', 'tile', 'glass', 'brick', 'beam', 'house', 'cement', '++', '--', 'write', 'view', 'if', 'room', 'door', 'ground', 'for', 'while', 'do', 'crack', 'mend', 'home'},
    '<continue_statement>': {'wall', 'id', '}', 'tile', 'glass', 'brick', 'beam', 'house', 'cement', '++', '--', 'write', 'view', 'if', 'room', 'door', 'ground', 'for', 'while', 'do', 'crack', 'mend', 'home'},
    '<return_statement>': {'wall', 'id', '}', 'tile', 'glass', 'brick', 'beam', 'house', 'cement', '++', '--', 'write', 'view', 'if', 'room', 'door', 'ground', 'for', 'while', 'do', 'crack', 'mend', 'home'},
    '<home_value>': {')', ';', ','},
}