PREDICT_SET = {
    '<program>': ['wall', 'roof', 'tile', 'glass', 'brick', 'beam', 'field'],
    '<program_body>': ['wall'],
    '<program_body_1>': ['tile', 'glass', 'brick', 'beam', 'field'],
    '<program_body2>': ['id'],
    '<program_body2_1>': ['blueprint'],
    '<global>': ['roof'],
    '<global_1>': ['wall', 'tile', 'glass', 'brick', 'beam', 'field'],
    '<global_dec>': ['wall', 'tile', 'glass', 'brick', 'beam'],
    '<global_dec_1>': ['house'],
    '<global_dec_2>': ['cement'],
    '<global_var>': ['tile', 'glass', 'brick', 'beam'],
    '<global_var_1>': ['wall'],
    '<data_type>': ['tile'],
    '<data_type_1>': ['glass'],
    '<data_type_2>': ['brick'],
    '<data_type_3>': ['beam'],
    '<global_end>': [';', '=', ','],
    '<global_end_1>': ['['],
    '<global_init>': ['='],
    '<global_init_1>': [';', ','],
    '<global_mult>': [','],
    '<global_mult_1>': [';'],
    '<value>': ['tile_lit'],
    '<value_1>': ['glass_lit'],
    '<value_2>': ['brick_lit'],
    '<value_3>': ['solid'],
    '<value_4>': ['fragile'],
    '<array_dec>': ['['],
    '<arr_size>': [']'],
    '<arr_size_1>': ['tile_lit'],
    '<one_d_end>': ['['],
    '<one_d_end_1>': ['='],
    '<one_d_end2>': ['['],
    '<one_d_end2_1>': ['='],
    '<one_d_end2_2>': [';'],
    '<two_d_end>': ['='],
    '<two_d_end_1>': [';'],
    '<elements>': ['tile_lit', 'glass_lit', 'brick_lit', 'solid', 'fragile'],
    '<mult_elem>': [','],
    '<mult_elem_1>': ['}'],
    '<mult_elem2>': [','],
    '<mult_elem2_1>': ['}'],
    '<global_wall_end>': [';', '=', ','],
    '<global_wall_end_1>': ['['],
    '<global_wall_init>': ['='],
    '<global_wall_init_1>': [';', ','],
    '<global_mult_wall>': [','],
    '<global_mult_wall_1>': [';'],
    '<wall_array>': ['['],
    '<wall_size>': [']'],
    '<wall_size_1>': ['tile_lit'],
    '<wall_one_d_end>': ['['],
    '<wall_one_d_end_1>': ['='],
    '<wall_one_d_end2>': ['['],
    '<wall_one_d_end2_1>': ['='],
    '<wall_one_d_end2_2>': [';'],
    '<wall_two_d_end>': ['='],
    '<wall_two_d_end_1>': [';'],
    '<wall_elem>': ['wall_lit'],
    '<wall_mult_elem>': [','],
    '<wall_mult_elem_1>': ['}'],
    '<wall_mult_elem2>': [','],
    '<wall_mult_elem2_1>': ['}'],
    '<structure>': ['house'],
    '<struct_type>': ['{'],
    '<struct_type_1>': ['id'],
    '<struct_dec>': ['{'],
    '<struct_members>': ['wall', 'tile', 'glass', 'brick', 'beam'],
    '<data_type_dec>': ['tile', 'glass', 'brick', 'beam'],
    '<data_type_dec_1>': ['wall'],
    '<array>': ['['],
    '<array_1>': [';'],
    '<array2>': ['['],
    '<array2_1>': [';'],
    '<mult_members>': ['wall', 'tile', 'glass', 'brick', 'beam'],
    '<mult_members_1>': ['}'],
    '<struct_id_end>': ['id'],
    '<struct_id_end_1>': [';'],
    '<struct_init>': ['='],
    '<struct_init_1>': [';', ','],
    '<struct_elem>': ['tile_lit', 'glass_lit', 'brick_lit', 'solid', 'fragile', 'wall_lit'],
    '<struct_elem_1>': ['{'],
    '<struct_value>': ['tile_lit', 'glass_lit', 'brick_lit', 'solid', 'fragile'],
    '<struct_value_1>': ['wall_lit'],
    '<mult_struct_elem>': [','],
    '<mult_struct_elem_1>': ['}'],
    '<struct_arr_elem>': ['tile_lit', 'glass_lit', 'brick_lit', 'solid', 'fragile', 'wall_lit'],
    '<struct_arr_elem_1>': ['{'],
    '<struct_elements>': ['tile_lit', 'glass_lit', 'brick_lit', 'solid', 'fragile', 'wall_lit'],
    '<struct_mult_elem>': [','],
    '<struct_mult_elem_1>': ['}'],
    '<struct_mult_elem2>': [','],
    '<struct_mult_elem2_1>': ['}'],
    '<mult_struct_id>': [','],
    '<mult_struct_id_1>': [';'],
    '<struct_var>': ['id'],
    '<global_const>': ['cement'],
    '<global_const_type>': ['tile', 'glass', 'brick', 'beam'],
    '<global_const_type_1>': ['wall'],
    '<global_const_type_2>': ['house'],
    '<global_const_end>': ['='],
    '<global_const_end_1>': ['['],
    '<global_mult_const>': [','],
    '<global_mult_const_1>': [';'],
    '<global_const_end2>': ['='],
    '<global_const_end2_1>': ['['],
    '<g_const_wall_end>': ['='],
    '<g_const_wall_end_1>': ['['],
    '<g_mult_const_wall>': [','],
    '<g_mult_const_wall_1>': [';'],
    '<g_const_wall_end2>': ['='],
    '<g_const_wall_end2_1>': ['['],
    '<global_const_struct>': [','],
    '<global_const_struct_1>': [';'],
    '<return_type>': ['tile', 'glass', 'brick', 'beam'],
    '<return_type_1>': ['field'],
    '<param_list>': ['wall', 'tile', 'glass', 'brick', 'beam'],
    '<param_list_1>': [')'],
    '<mult_param>': [','],
    '<mult_param_1>': [')'],
    '<func_body>': ['wall', 'tile', 'glass', 'brick', 'beam', 'house', 'cement'],
    '<func_body_1>': ['id', '++', '--', 'write', 'view', 'if', 'room', 'for', 'while', 'do', 'crack', 'mend', 'home'],
    '<func_body2>': ['wall', 'id', 'tile', 'glass', 'brick', 'beam', 'house', 'cement', '++', '--', 'write', 'view', 'if', 'room', 'for', 'while', 'do', 'crack', 'mend', 'home'],
    '<func_body2_1>': ['}'],
    '<local>': ['wall', 'tile', 'glass', 'brick', 'beam', 'house', 'cement'],
    '<declaration>': ['wall', 'tile', 'glass', 'brick', 'beam'],
    '<declaration_1>': ['house'],
    '<declaration_2>': ['cement'],
    '<variable>': ['tile', 'glass', 'brick', 'beam'],
    '<variable_1>': ['wall'],
    '<var_end>': [';', '=', ','],
    '<var_end_1>': ['['],
    '<initializer>': ['='],
    '<initializer_1>': [';', ','],
    '<mult_var>': [','],
    '<mult_var_1>': [';'],
    '<expression>': ['id'],
    '<expression_1>': ['('],
    '<expression_2>': ['tile_lit', 'glass_lit', 'brick_lit', 'solid', 'fragile', '-'],
    '<expression_3>': ['++', '--', '!'],
    '<value_exp>': ['tile_lit', 'glass_lit', 'brick_lit', 'solid', 'fragile'],
    '<value_exp_1>': ['-'],
    '<id_type>': ['(', ')', ';', ',', '[', ']', '-', '.', '++', '--', '+', '*', '/', '%', '<', '<=', '==', '>', '>=', '!=', '&&', '||'],
    '<id_type_1>': [')', ';', ',', ']', '-', '+', '*', '/', '%', '<', '<=', '>', '>=', '==', '!=', '&&', '||'],
    '<id_type2>': [')', ';', ',', '[', ']', '-', '.', '++', '--', '+', '*', '/', '%', '<', '<=', '>', '>=', '==', '!=', '&&', '||'],
    '<id_type2_1>': ['(', ')', ';', ',', ']', '-', '+', '*', '/', '%', '<', '<=', '>', '>=', '==', '!=', '&&', '||'],
    '<arr_struct>': [')', ';', ',', '[', ']', '-', '++', '--', '+', '*', '/', '%', '<', '<=', '>', '>=', '==', '!=', '&&', '||'],
    '<arr_struct_1>': [')', ';', ',', ']', '-', '.', '++', '--', '+', '*', '/', '%', '<', '<=', '>', '>=', '==', '!=', '&&', '||'],
    '<array_index>': ['['],
    '<array_index_1>': [')', ';', '=', ',', ']', '-', '++', '--', '+', '*', '/', '%', '<', '<=', '>', '>=', '==', '!=', '&&', '||', '+=', '-=', '*=', '/=', '%='],
    '<array_index2>': ['['],
    '<array_index2_1>': [')', ';', '=', ',', ']', '-', '++', '--', '+', '*', '/', '%', '<', '<=', '>', '>=', '==', '!=', '&&', '||', '+=', '-=', '*=', '/=', '%='],
    '<struct_id>': ['.'],
    '<struct_id_1>': [')', ';', '=', ',', ']', '-', '++', '--', '+', '*', '/', '%', '<', '<=', '>', '>=', '==', '!=', '&&', '||', '+=', '-=', '*=', '/=', '%='],
    '<func_call>': ['('],
    '<func_call_1>': [')', ';', ',', ']', '-', '+', '*', '/', '%', '<', '<=', '>', '>=', '==', '!=', '&&', '||'],
    '<func_argu>': ['id', '(', 'tile_lit', 'glass_lit', 'brick_lit', 'solid', 'fragile', 'wall_lit', '-', '++', '--', '!'],
    '<func_argu_1>': [')'],
    '<func_mult_call>': [','],
    '<func_mult_call_1>': [')'],
    '<postfix_op>': ['++', '--'],
    '<postfix_op_1>': [')', ';', ',', ']', '-', '+', '*', '/', '%', '<', '<=', '>', '>=', '==', '!=', '&&', '||'],
    '<unary_op>': ['++'],
    '<unary_op_1>': ['--'],
    '<exp_op>': ['-', '+', '*', '/', '%', '<', '<=', '>', '>=', '==', '!=', '&&', '||'],
    '<exp_op_1>': [')', ';', ',', ']', '-', '+', '*', '/', '%', '<', '<=', '>', '>=', '==', '!=', '&&', '||'],
    '<prefix_op>': ['!'],
    '<prefix_op_1>': ['++', '--'],
    '<prefix_exp>': ['('],
    '<prefix_exp_1>': ['id'],
    '<id_val>': ['id'],
    '<id_type3>': [')', ';', '=', ',', '[', ']', '-', '+', '*', '/', '%', '<', '<=', '>', '>=', '==', '!=', '&&', '||', '+=', '-=', '*=', '/=', '%='],
    '<id_type3_1>': [')', ';', '=', ',', ']', '-', '.', '+', '*', '/', '%', '<', '<=', '>', '>=', '==', '!=', '&&', '||', '+=', '-=', '*=', '/=', '%='],
    '<id_type3_2>': [')', ';', '=', ',', ']', '-', '+', '*', '/', '%', '<', '<=', '>', '>=', '==', '!=', '&&', '||', '+=', '-=', '*=', '/=', '%='],
    '<operator>': ['+'],
    '<operator_1>': ['-'],
    '<operator_2>': ['*'],
    '<operator_3>': ['/'],
    '<operator_4>': ['%'],
    '<operator_5>': ['<'],
    '<operator_6>': ['<='],
    '<operator_7>': ['>'],
    '<operator_8>': ['>='],
    '<operator_9>': ['=='],
    '<operator_10>': ['!='],
    '<operator_11>': ['&&'],
    '<operator_12>': ['||'],
    '<wall_end>': [';', '=', ','],
    '<wall_end_1>': ['['],
    '<wall_initializer>': ['='],
    '<wall_initializer_1>': [';', ','],
    '<wall_init>': ['('],
    '<wall_init_1>': ['wall_lit'],
    '<wall_init_2>': ['id'],
    '<wall_op>': ['+'],
    '<wall_op_1>': [')', ';', ','],
    '<mult_wall>': [','],
    '<mult_wall_1>': [';'],
    '<constant>': ['cement'],
    '<const_type>': ['tile', 'glass', 'brick', 'beam'],
    '<const_type_1>': ['wall'],
    '<const_type_2>': ['house'],
    '<const_end>': ['='],
    '<const_end_1>': ['['],
    '<mult_const>': [','],
    '<mult_const_1>': [';'],
    '<const_wall_end>': ['='],
    '<const_wall_end_1>': ['['],
    '<mult_const_struct>': [','],
    '<mult_const_struct_1>': [';'],
    '<statement>': ['write', 'view'],
    '<statement_1>': ['id', '++', '--'],
    '<statement_2>': ['if'],
    '<statement_3>': ['room'],
    '<statement_4>': ['for'],
    '<statement_5>': ['while'],
    '<statement_6>': ['do'],
    '<statement_7>': ['crack'],
    '<statement_8>': ['mend'],
    '<statement_9>': ['home'],
    '<io_statement>': ['write'],
    '<io_statement_1>': ['view'],
    '<write_argu>': ['&'],
    '<write_argu_1>': ['id'],
    '<mult_write_argu>': [','],
    '<mult_write_argu_1>': [')'],
    '<view_argu>': [','],
    '<view_argu_1>': [')'],
    '<mult_view_argu>': [')', ','],
    '<mult_view_argu_1>': [')'],
    '<assign_statement>': ['++', '--'],
    '<assign_statement_1>': ['id'],
    '<id_type4>': ['('],
    '<id_type4_1>': ['++', '--'],
    '<id_type4_2>': ['=', '[', '.', '+=', '-=', '*=', '/=', '%='],
    '<assign_end>': ['+=', '-=', '*=', '/=', '%='],
    '<assign_end_1>': ['='],
    '<compound_op>': ['+='],
    '<compound_op_1>': ['-='],
    '<compound_op_2>': ['*='],
    '<compound_op_3>': ['/='],
    '<compound_op_4>': ['%='],
    '<assign_rhs>': ['id'],
    '<assign_rhs_1>': ['('],
    '<assign_rhs_2>': ['tile_lit', 'glass_lit', 'brick_lit', 'solid', 'fragile', '-'],
    '<assign_rhs_3>': ['++', '--', '!'],
    '<assign_rhs_4>': ['wall_lit'],
    '<assign_exp>': ['-', '+', '*', '/', '%', '<', '<=', '>', '>=', '==', '!=', '&&', '||'],
    '<assign_exp_1>': [')', ';', ','],
    '<if_statement>': ['if'],
    '<else_statement>': ['else'],
    '<else_statement_1>': ['wall', 'id', '}', 'tile', 'glass', 'brick', 'beam', 'house', 'cement', '++', '--', 'write', 'view', 'if', 'room', 'door', 'ground', 'for', 'while', 'do', 'crack', 'mend', 'home'],
    '<else_statement2>': ['if'],
    '<else_statement2_1>': ['{'],
    '<switch_statement>': ['room'],
    '<switch_body>': ['door'],
    '<switch_body_1>': ['ground'],
    '<mult_switch_body>': ['door', 'ground'],
    '<mult_switch_body_1>': ['}'],
    '<case_val>': ['tile_lit'],
    '<case_val_1>': ['brick_lit'],
    '<case_val_2>': ['solid'],
    '<case_val_3>': ['fragile'],
    '<case_body>': ['id', '++', '--', 'write', 'view', 'if', 'room', 'for', 'while', 'do', 'crack', 'mend', 'home'],
    '<case_body_1>': ['{'],
    '<case_body_2>': ['}', 'door', 'ground'],
    '<mult_smt>': ['id', '++', '--', 'write', 'view', 'if', 'room', 'for', 'while', 'do', 'crack', 'mend', 'home'],
    '<mult_smt_1>': ['}', 'door', 'ground'],
    '<for_statement>': ['for'],
    '<for_dec>': ['tile', 'glass', 'brick', 'beam'],
    '<for_dec_1>': ['id'],
    '<while_statement>': ['while'],
    '<dowhile_statement>': ['do'],
    '<break_statement>': ['crack'],
    '<continue_statement>': ['mend'],
    '<return_statement>': ['home'],
}