PREDICT_SET = {
    '<arr_size>': [']'],
    '<arr_size_1>': ['tile_lit'],
    '<arr_struct>': ['!=', '%', '&&', ')', '*', '+', '++', '-', '--', '/', ';', '<', '<=', '==', '>', '>=', '[', ']', '||'],
    '<arr_struct_1>': ['!=', '%', '&&', ')', '*', '+', '++', '-', '--', '.', '/', ';', '<', '<=', '==', '>', '>=', ']', '||'],
    '<arr_struct_2>': ['!=', '%', '&&', ')', '*', '+', '++', '-', '--', '/', ';', '<', '<=', '==', '>', '>=', ']', '||'],
    '<array2>': ['['],
    '<array2_1>': [';'],
    '<array>': ['['],
    '<array_1>': [';'],
    '<array_dec>': ['['],
    '<array_index2>': ['['],
    '<array_index2_1>': ['!=', '%', '%=', '&&', ')', ',', '*', '*=', '+', '++', '+=', '-', '--', '-=', '/', '/=', ';', '<', '<=', '=', '==', '>', '>=', ']', '||'],
    '<array_index>': ['['],
    '<array_index_1>': ['!=', '%', '%=', '&&', ')', '*', '*=', '+', '++', '+=', '-', '--', '-=', '/', '/=', ';', '<', '<=', '=', '==', '>', '>=', ']', '||'],
    '<assign_op>': ['='],
    '<assign_op_1>': ['+='],
    '<assign_op_2>': ['-='],
    '<assign_op_3>': ['*='],
    '<assign_op_4>': ['/='],
    '<assign_op_5>': ['%='],
    '<assign_statement>': ['++', '--'],
    '<assign_statement_1>': ['id'],
    '<assign_value>': ['!', '(', '++', '-', '--', 'brick_lit', 'fragile', 'glass_lit', 'id', 'solid', 'tile_lit'],
    '<assign_value_1>': ['(', 'brick_lit', 'id', 'wall_lit'],
    '<break_statement>': ['crack'],
    '<case_body>': ['++', '--', 'crack', 'do', 'for', 'home', 'id', 'if', 'mend', 'room', 'view', 'while', 'write'],
    '<case_body_1>': ['{'],
    '<case_body_2>': ['door', 'ground', '}'],
    '<case_exp>': ['(', '-', 'brick_lit', 'fragile', 'solid', 'tile_lit'],
    '<case_group>': ['('],
    '<case_negative>': ['brick_lit', 'fragile', 'solid', 'tile_lit'],
    '<case_negative_1>': ['('],
    '<case_op>': ['!=', '%', '&&', '*', '+', '-', '/', '<', '<=', '==', '>', '>=', '||'],
    '<case_op_1>': [')', ':'],
    '<case_type>': ['brick_lit', 'fragile', 'solid', 'tile_lit'],
    '<case_type_1>': ['('],
    '<case_type_2>': ['-'],
    '<case_val>': ['tile_lit'],
    '<case_val_1>': ['brick_lit'],
    '<case_val_2>': ['solid'],
    '<case_val_3>': ['fragile'],
    '<const_end>': ['='],
    '<const_end_1>': ['['],
    '<const_type>': ['beam', 'brick', 'glass', 'tile'],
    '<const_type_1>': ['wall'],
    '<const_type_2>': ['house'],
    '<const_wall_end>': ['='],
    '<const_wall_end_1>': ['['],
    '<constant>': ['cement'],
    '<continue_statement>': ['mend'],
    '<data_type>': ['tile'],
    '<data_type_1>': ['glass'],
    '<data_type_2>': ['brick'],
    '<data_type_3>': ['beam'],
    '<data_type_dec>': ['beam', 'brick', 'glass', 'tile'],
    '<data_type_dec_1>': ['wall'],
    '<declaration>': ['beam', 'brick', 'glass', 'tile', 'wall'],
    '<declaration_1>': ['house'],
    '<declaration_2>': ['cement'],
    '<dowhile_statement>': ['do'],
    '<elements>': ['brick_lit', 'fragile', 'glass_lit', 'solid', 'tile_lit'],
    '<else_statement2>': ['if'],
    '<else_statement2_1>': ['{'],
    '<else_statement>': ['else'],
    '<else_statement_1>': ['++', '--', 'beam', 'brick', 'cement', 'crack', 'do', 'door', 'for', 'glass', 'ground', 'home', 'house', 'id', 'if', 'mend', 'room', 'tile', 'view', 'wall', 'while', 'write', '}'],
    '<exp_op>': ['!=', '%', '&&', '*', '+', '-', '/', '<', '<=', '==', '>', '>=', '||'],
    '<exp_op_1>': [')', ';', ']'],
    '<for_dec>': ['beam', 'brick', 'glass', 'tile'],
    '<for_dec_1>': ['id'],
    '<for_statement>': ['for'],
    '<func_argu>': ['!', '(', '++', '-', '--', 'brick_lit', 'fragile', 'glass_lit', 'id', 'solid', 'tile_lit'],
    '<func_argu_1>': ['(', 'brick_lit', 'id', 'wall_lit'],
    '<func_argu_2>': [')'],
    '<func_body2>': ['++', '--', 'beam', 'brick', 'cement', 'crack', 'do', 'for', 'glass', 'home', 'house', 'id', 'if', 'mend', 'room', 'tile', 'view', 'wall', 'while', 'write'],
    '<func_body2_1>': ['}'],
    '<func_body>': ['beam', 'brick', 'cement', 'glass', 'house', 'tile', 'wall'],
    '<func_body_1>': ['++', '--', 'crack', 'do', 'for', 'home', 'id', 'if', 'mend', 'room', 'view', 'while', 'write'],
    '<func_call>': ['('],
    '<func_call_1>': ['!=', '%', '&&', ')', '*', '+', '-', '/', ';', '<', '<=', '==', '>', '>=', ']', '||'],
    '<func_mult_call>': [','],
    '<func_mult_call_1>': [','],
    '<func_mult_call_2>': [')'],
    '<g_const_wall_end2>': ['='],
    '<g_const_wall_end2_1>': ['['],
    '<g_const_wall_end>': ['='],
    '<g_const_wall_end_1>': ['['],
    '<g_mult_const_wall>': [','],
    '<g_mult_const_wall_1>': [';'],
    '<global>': ['roof'],
    '<global_1>': ['beam', 'brick', 'field', 'glass', 'tile', 'wall'],
    '<global_const>': ['cement'],
    '<global_const_end2>': ['='],
    '<global_const_end2_1>': ['['],
    '<global_const_end>': ['='],
    '<global_const_end_1>': ['['],
    '<global_const_struct>': [','],
    '<global_const_struct_1>': [';'],
    '<global_const_type>': ['beam', 'brick', 'glass', 'tile'],
    '<global_const_type_1>': ['wall'],
    '<global_const_type_2>': ['house'],
    '<global_dec>': ['beam', 'brick', 'glass', 'tile', 'wall'],
    '<global_dec_1>': ['house'],
    '<global_dec_2>': ['cement'],
    '<global_end>': [';', '='],
    '<global_end_1>': ['['],
    '<global_init>': ['='],
    '<global_init_1>': [';'],
    '<global_mult>': [','],
    '<global_mult_1>': [';'],
    '<global_mult_const>': [','],
    '<global_mult_const_1>': [';'],
    '<global_mult_wall>': [','],
    '<global_mult_wall_1>': [';'],
    '<global_var>': ['beam', 'brick', 'glass', 'tile'],
    '<global_var_1>': ['wall'],
    '<global_wall_end>': [';', '='],
    '<global_wall_end_1>': ['['],
    '<global_wall_init>': ['='],
    '<global_wall_init_1>': [';'],
    '<group>': ['('],
    '<home_value>': ['!', '(', '++', '-', '--', 'brick_lit', 'fragile', 'glass_lit', 'id', 'solid', 'tile_lit'],
    '<home_value_1>': ['(', 'brick_lit', 'id', 'wall_lit'],
    '<id_type2>': ['!=', '%', '&&', ')', '*', '+', '++', '-', '--', '.', '/', ';', '<', '<=', '==', '>', '>=', '[', ']', '||'],
    '<id_type2_1>': ['!=', '%', '&&', '(', ')', '*', '+', '-', '/', ';', '<', '<=', '==', '>', '>=', ']', '||'],
    '<id_type3>': ['!=', '%', '%=', '&&', ')', '*', '*=', '+', '+=', '-', '-=', '/', '/=', ';', '<', '<=', '=', '==', '>', '>=', '[', ']', '||'],
    '<id_type3_1>': ['!=', '%', '%=', '&&', ')', '*', '*=', '+', '+=', '-', '-=', '.', '/', '/=', ';', '<', '<=', '=', '==', '>', '>=', ']', '||'],
    '<id_type3_2>': ['!=', '%', '%=', '&&', ')', '*', '*=', '+', '+=', '-', '-=', '/', '/=', ';', '<', '<=', '=', '==', '>', '>=', ']', '||'],
    '<id_type4>': ['('],
    '<id_type4_1>': ['++', '--'],
    '<id_type4_2>': ['%=', '*=', '+=', '-=', '.', '/=', '=', '['],
    '<id_type>': ['!=', '%', '&&', '(', ')', '*', '+', '++', '-', '--', '.', '/', ';', '<', '<=', '==', '>', '>=', '[', ']', '||'],
    '<id_type_1>': ['!=', '%', '&&', ')', '*', '+', '-', '/', ';', '<', '<=', '==', '>', '>=', ']', '||'],
    '<id_val>': ['id'],
    '<if_statement>': ['if'],
    '<init_value>': ['(', '-', 'brick_lit', 'fragile', 'glass_lit', 'id', 'solid', 'tile_lit'],
    '<init_value_1>': ['!', '++', '--'],
    '<initializer>': ['='],
    '<initializer_1>': [';'],
    '<io_statement>': ['write'],
    '<io_statement_1>': ['view'],
    '<local>': ['beam', 'brick', 'cement', 'glass', 'house', 'tile', 'wall'],
    '<mult_const>': [','],
    '<mult_const_1>': [';'],
    '<mult_const_struct>': [','],
    '<mult_const_struct_1>': [';'],
    '<mult_elem2>': [','],
    '<mult_elem2_1>': ['}'],
    '<mult_elem>': [','],
    '<mult_elem_1>': ['}'],
    '<mult_members>': ['beam', 'brick', 'glass', 'tile', 'wall'],
    '<mult_members_1>': ['}'],
    '<mult_param>': [','],
    '<mult_param_1>': [')'],
    '<mult_smt>': ['++', '--', 'crack', 'do', 'for', 'home', 'id', 'if', 'mend', 'room', 'view', 'while', 'write'],
    '<mult_smt_1>': ['door', 'ground', '}'],
    '<mult_struct_elem>': [','],
    '<mult_struct_elem_1>': ['}'],
    '<mult_struct_id>': [','],
    '<mult_struct_id_1>': [';'],
    '<mult_switch_body>': ['door', 'ground'],
    '<mult_switch_body_1>': ['}'],
    '<mult_var>': [','],
    '<mult_var_1>': [';'],
    '<mult_view_argu>': [')'],
    '<mult_view_argu_1>': [')'],
    '<mult_wall>': [','],
    '<mult_wall_1>': [';'],
    '<mult_write_argu>': [','],
    '<mult_write_argu_1>': [')'],
    '<negative_type>': ['brick_lit', 'fragile', 'glass_lit', 'id', 'solid', 'tile_lit'],
    '<negative_type_1>': ['('],
    '<one_d_end2>': ['['],
    '<one_d_end2_1>': ['='],
    '<one_d_end2_2>': [';'],
    '<one_d_end>': ['['],
    '<one_d_end_1>': ['='],
    '<operator>': ['+'],
    '<operator_10>': ['!='],
    '<operator_11>': ['&&'],
    '<operator_12>': ['||'],
    '<operator_1>': ['-'],
    '<operator_2>': ['*'],
    '<operator_3>': ['/'],
    '<operator_4>': ['%'],
    '<operator_5>': ['<'],
    '<operator_6>': ['<='],
    '<operator_7>': ['>'],
    '<operator_8>': ['>='],
    '<operator_9>': ['=='],
    '<param_list>': ['beam', 'brick', 'glass', 'tile', 'wall'],
    '<param_list_1>': [')'],
    '<postfix_op>': ['++', '--'],
    '<postfix_op_1>': ['!=', '%', '&&', ')', '*', '+', '-', '/', ';', '<', '<=', '==', '>', '>=', ']', '||'],
    '<prefix_op>': ['!'],
    '<prefix_op_1>': ['++', '--'],
    '<program>': ['beam', 'brick', 'field', 'glass', 'roof', 'tile', 'wall'],
    '<program_body2>': ['id'],
    '<program_body2_1>': ['blueprint'],
    '<program_body>': ['wall'],
    '<program_body_1>': ['beam', 'brick', 'field', 'glass', 'tile'],
    '<return_statement>': ['home'],
    '<return_type>': ['beam', 'brick', 'glass', 'tile'],
    '<return_type_1>': ['field'],
    '<statement>': ['view', 'write'],
    '<statement_1>': ['++', '--', 'id'],
    '<statement_2>': ['if'],
    '<statement_3>': ['room'],
    '<statement_4>': ['for'],
    '<statement_5>': ['while'],
    '<statement_6>': ['do'],
    '<statement_7>': ['crack'],
    '<statement_8>': ['mend'],
    '<statement_9>': ['home'],
    '<struct_arr_elem>': ['brick_lit', 'fragile', 'glass_lit', 'solid', 'tile_lit', 'wall_lit'],
    '<struct_arr_elem_1>': ['{'],
    '<struct_dec>': ['{'],
    '<struct_elem>': ['brick_lit', 'fragile', 'glass_lit', 'solid', 'tile_lit', 'wall_lit'],
    '<struct_elem_1>': ['{'],
    '<struct_elements>': ['brick_lit', 'fragile', 'glass_lit', 'solid', 'tile_lit', 'wall_lit'],
    '<struct_id>': ['.'],
    '<struct_id_1>': ['!=', '%', '%=', '&&', ')', '*', '*=', '+', '++', '+=', '-', '--', '-=', '/', '/=', ';', '<', '<=', '=', '==', '>', '>=', ']', '||'],
    '<struct_id_end>': ['id'],
    '<struct_id_end_1>': [';'],
    '<struct_init>': ['='],
    '<struct_init_1>': [';'],
    '<struct_members>': ['beam', 'brick', 'glass', 'tile', 'wall'],
    '<struct_mult_elem2>': [','],
    '<struct_mult_elem2_1>': ['}'],
    '<struct_mult_elem>': [','],
    '<struct_mult_elem_1>': ['}'],
    '<struct_type>': ['{'],
    '<struct_type_1>': ['id'],
    '<struct_value>': ['brick_lit', 'fragile', 'glass_lit', 'solid', 'tile_lit'],
    '<struct_value_1>': ['wall_lit'],
    '<struct_var>': ['id'],
    '<structure>': ['house'],
    '<switch_body>': ['door'],
    '<switch_body_1>': ['ground'],
    '<switch_statement>': ['room'],
    '<two_d_end>': ['='],
    '<two_d_end_1>': [';'],
    '<unary_op>': ['++'],
    '<unary_op_1>': ['--'],
    '<value>': ['tile_lit'],
    '<value_1>': ['glass_lit'],
    '<value_2>': ['brick_lit'],
    '<value_3>': ['solid'],
    '<value_4>': ['fragile'],
    '<value_exp>': ['brick_lit', 'fragile', 'glass_lit', 'id', 'solid', 'tile_lit'],
    '<value_exp_1>': ['('],
    '<value_exp_2>': ['-'],
    '<value_type>': ['id'],
    '<value_type_1>': ['brick_lit', 'fragile', 'glass_lit', 'solid', 'tile_lit'],
    '<var_end>': [';', '='],
    '<var_end_1>': ['['],
    '<variable>': ['beam', 'brick', 'glass', 'tile'],
    '<variable_1>': ['wall'],
    '<view_argu>': [','],
    '<view_argu_1>': [')'],
    '<wall_array>': ['['],
    '<wall_elem>': ['wall_lit'],
    '<wall_end>': [';', '='],
    '<wall_end_1>': ['['],
    '<wall_init>': ['('],
    '<wall_init_1>': ['wall_lit'],
    '<wall_init_2>': ['brick_lit'],
    '<wall_init_3>': ['id'],
    '<wall_initializer>': ['='],
    '<wall_initializer_1>': [';'],
    '<wall_mult_elem2>': [','],
    '<wall_mult_elem2_1>': ['}'],
    '<wall_mult_elem>': [','],
    '<wall_mult_elem_1>': ['}'],
    '<wall_one_d_end2>': ['['],
    '<wall_one_d_end2_1>': ['='],
    '<wall_one_d_end2_2>': [';'],
    '<wall_one_d_end>': ['['],
    '<wall_one_d_end_1>': ['='],
    '<wall_op>': ['+'],
    '<wall_op_1>': [')', ',', ';'],
    '<wall_rhs>': ['('],
    '<wall_rhs_1>': ['wall_lit'],
    '<wall_rhs_2>': ['brick_lit'],
    '<wall_rhs_3>': ['id'],
    '<wall_size>': [']'],
    '<wall_size_1>': ['tile_lit'],
    '<wall_two_d_end>': ['='],
    '<wall_two_d_end_1>': [';'],
    '<while_statement>': ['while'],
    '<write_argu>': ['&'],
    '<write_argu_1>': ['id'],
}
